services:
  - type: worker
    name: pikachu-music
    env: python
    region: oregon
    plan: free
    buildCommand: |
      curl -Ls https://astral.sh/uv/install.sh | sh
      export PATH="$HOME/.local/bin:$PATH"
      uv sync --frozen
      apt-get update && apt-get install -y ffmpeg
    startCommand: |
      export PATH="$HOME/.local/bin:$PATH"
      uv run python3 -m anony
    autoDeploy: true

    envVars:
      # Required Core Variables
      API_ID:
        value: 37167486
      API_HASH:
        value: 4110067d89bd1b5f43171e67e67aa01f
      BOT_TOKEN:
        sync: false
      OWNER_ID:
        value: 7065156396
      LOGGER_ID:
        value: -1004296750499
      MONGO_URL:
        value: mongodb+srv://Musicbot:musicbot123@cluster0.njyarc8.mongodb.net/?appName=Cluster0
      SESSION:
        sync: false
      
      # Optional Support Variables
      SUPPORT_GROUP:
        value: https://t.me/+UhZo8ZsUECYyYWI1
      SUPPORT_CHANNEL:
        value: https://t.me/PikachuuBotUpdates
